# Generated by Django 4.1.7 on 2023-03-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dmvpn", "0002_remove_user_password_user_password_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password_hash",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
