# Generated by Django 4.1.7 on 2023-03-27 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dmvpn", "0003_alter_user_password_hash"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="password_hash",
        ),
    ]
