# Generated by Django 4.1.7 on 2023-03-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dmvpn", "0004_remove_user_password_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=100, null="True"),
            preserve_default="True",
        ),
    ]
