# Generated by Django 4.1.7 on 2023-03-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dmvpn", "0005_user_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="Credentials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
